### ISSUE TITLE
Player owns a hand of Warzonecards (see Part 5)

### ISSUE THREAD

**Issue by miche-cho** [PinMeister/COMP-345-Project#10]
Each  card  has  a  type from: bomb,  reinforcement,  blockade, airlift and diplomacy.  The  deck  must  have  a  draw() method  that  allows  a  player  to  draw  a  card  at  random  from  the  cards  remaining  in  the  deck  and  place  it  in their  hand  of  cards.

Imports Hand and Warzone cards

**Comment by KevinHTrinh** [comment]
Player has an object Hand, and the Hand object has a vector of cards.
